name: flutter_firebase_app
description: A Flutter app with Firebase authentication

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.10.0
  firebase_auth: ^5.5.0
  cloud_firestore: ^4.8.0
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/  # Add your asset images here if needed
    - assets/icons/   # Add your asset icons here if needed